### ISSUE TITLE
Plugin gui produces corrupt .continuous files for plugin gui 0.4.1

### ISSUE THREAD

**Issue by galenlynch** [open-ephys/plugin-GUI#125] opened 2017-03-18 15:56 UTC
I have noticed that for some of my recordings, the .continuous files from the same recording have different sizes on disk, corresponding to different numbers of complete data blocks. Often, the smaller files cannot possibly be comprised of complete data blocks. Even before the truncted block in a damaged file, the surviving blocks have defects such as an incorrect end or record marker (all zeros instead of the sequence specified), or other problems.

**Comment by aacuevas** [comment] 2017-03-22 23:31
Hi,

This is the fitst notice we have of similar issues with the open-ephys format. Even when blocks are missing the basic file structure should be stable. 

Do you know if the file corruption happens randomly or is there any correlation with another event?
What are the OS and the computer specs you're using?
Could you please send me ( aaron@open-ephys.org ) the settings.xml file and one of the corrupted .continuous files?

Aarón.

**Comment by galenlynch** [comment] 2017-04-26 18:03
Sorry that it took me so long to respond to this. I sent you the corrupt .continuous file and settings.xml file. I can reliably produce corrupt .continuous files by taking short recordings.

**Comment by jsiegle** [comment] 2017-04-26 19:16
How short is "short"? I think we've noticed a few problems related to recordings <2 minutes, presumably due to the buffering that happens inside the recording thread.

**Comment by aacuevas** [comment] 2017-04-26 19:19
I was about to ask the same question. In theory the recording system should work with short recordings, I've tested it with a couple of seconds, but there might still be some corner cases which cause this corruption. I'll take a look at the files and see if I can figure out something from them.

**Comment by galenlynch** [comment] 2017-04-26 19:40
The file that I just sent @aacuevas was 22 seconds long. I routinely take short recordings (10-20s) when testing for antidromic activation of neurons, which is mostly when I see this problem.

**Comment by galenlynch** [comment] 2017-04-27 18:29
I was looking at one of the corrupt files and realized that the timestamps in the corrupt files start 256 samples after the timestamps in the good files.

**Comment by jvoigts** [comment] 2017-08-24 02:15
This is likely a duplicate of https://github.com/open-ephys/plugin-GUI/issues/154 - could you check if the recent bugfix resolved this and close if that's the case?

**Comment by galenlynch** [comment] 2017-08-24 02:29
I will check in the next week. I also routinely turn off channels, it could very well be the same issue as #154.

**Closed** 2020-12-15 20:56 UTC
