### ISSUE TITLE
Adding Network Events causes system freeze upon start record in Plugin-GUI master

### ISSUE THREAD

**Issue by shayo** [open-ephys/plugin-GUI#139] opened 2017-06-26 14:51 UTC
I have a very simple chain (see attachment), but it seems like when I add network events and then hit record, the system freezes on OSX.
Removing the Network Events PlugIn solves the freezing.
I am not sure it is actually Network Event's fault. I.e., everything is running properly until I hit record. It looks like this might be related to issue #135 (files are not saved).

Can someone check / reproduce?

[not_working.txt](https://github.com/open-ephys/plugin-GUI/files/1102500/not_working.txt)

**Comment by shayo** [comment] 2017-06-26 15:18
This doesn't happen on the GUI-master branch.

**Comment by zekearneodo** [comment] 2017-08-13 03:36
Did you figure a workaround for this? I am having this issue (on OSX), using the master branch of plugin-GUI.

**Comment by shayo** [comment] 2017-08-13 18:21
No. I switched to a Windows machine :(

**Comment by c-wilson** [comment] 2017-09-13 22:52
Hey, I think this is a duplicate of #67 and is still an issue, but there is a workaround in that thread.

**Comment by zekearneodo** [comment] 2017-09-30 01:44
Indeed, that workaround works.
Thank you.

**Comment by jsiegle** [comment] 2020-12-16 22:08
Just tested on Mac, and this is no longer happening.

**Closed by jsiegle** 2020-12-16 22:08 UTC
