### ISSUE TITLE
Issues with splitters and mergers

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/plugin-GUI#377] opened 2020-10-06 11:37 UTC
In 0.5.1, loading a signal chain with splitter and/or mergers returns a mangled chain with most of the processors merged into a single branch. 

In addition, sometimes when dragging a splitter and then another processor, it ends on the second branch, instead of the intended current, first branch.

I have also encountered some crashes when trying to connect a merger to a different branch. I'll further test this.

**Comment by jsiegle** [comment] 2020-10-10 18:01
We figured out the cause of this issue...saving the signal chain calls `Splitter::switchIO()`, which means that updating the recovery config after adding each processor can change the state of the underlying signal chain. 

We will release a fix for this in the next few days.

**Comment by jsiegle** [comment] 2020-10-12 21:59
This is fixed in the latest development branch. Will leave this open until we merge the changes into master.

**Comment by jsiegle** [comment] 2020-10-20 17:09
This problem is fixed in v0.5.2. The installers are available [here](https://open-ephys.org/gui), or you can download the GUI as a .zip file [here](https://dl.bintray.com/open-ephys-gui/Release/).

**Closed by jsiegle** 2020-10-20 17:09 UTC
Labels: Bug, Ready for release
